# Site settings
title: Remix
email: youremail@yourdomain.net
description: 
type: website
image: /assets/imgs/octojekyll.jpg
host: 0.0.0.0
baseurl: "/"
# Server Config options
livereload: true
theme: minima
# SASS
sass:
  sass_dir: assets/_sass
  style: compressed


