name: Deploy

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build the project for development
        if: github.ref == 'refs/heads/development'
        run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to development
        if: github.ref == 'refs/heads/development'
        run: |
          aws s3 sync ./build  s3://remix-landing-development
          aws cloudfront create-invalidation --distribution-id E307SOOP3E3LYF --paths "/*"

      - name: Publish to Github pages
        run: npm run deploy
